Feature/us13
WildCodeSchool/lyon-js-03-20-p2-g3 pull request #34
Opened 2020-04-30 15:46 UTC by Astarosa

All good Pierre ! @ComicScrip

2020-05-03 11:01 UTC, ComicScrip requested changes

2020-05-03 11:01 UTC, ComicScrip commented on src/components/DeckBoard.js
> +    const newDeckIa = this.state.cardsAvalaibleForIA;
Vous faites des mutations sur le state, pas bon

2020-05-03 11:01 UTC, ComicScrip commented on src/components/DeckBoard.js
> +      i < newDeckIa.filter((heroe) => heroe.position === 'board').length;
Vous itérez sur quelque chose qui est modifié dans la boucle. Je vous conseille de passer par un tableau qui contiendra toutes les cartes à jouer pour l'IA, itérer sur ce dernier tant que le tableau n'est pas vide (on prendra la première carte du tableau des cartes "à traiter"  à chaque fois). Supprimer une carte du tableau quand c'est nécessaire (la carte est "morte" ou elle a été jouée).

2020-05-03 11:05 UTC, ComicScrip commented
Je me rends sur l'app, je fais "Play", je séléctionne les trois premieres cartes proposées, j'accède à la board, je place mes cartes sur le deck et j'attends la fin du timer. A un moment j'ai ça : 

![image](https://user-images.githubusercontent.com/16140010/80912600-59110d80-8d3e-11ea-8eea-77cb244915a0.png)

Et il y a des erreurs dans la console, merci de mieux vérifier.
Aussi, pourriez-vous me décrire les règles du jeu de façon précise ?

2020-05-03 12:36 UTC, Pascal-Pereira commented
@ComicScrip 
Merci pour cette attention dominicale. 
Nous avons résolu dans l'US n°11 ce conflit relatif à l'itération sur la boucle variable, ainsi que le 2ème  problème que tu as soulevé qui découlait du 1er.
Ceci n'est pas lié intrinsèquement à cette  US n°13 (relative au timer), et nous avons corrigé cela sur notre US n°11.

Pourrais tu stp nous dire s'il est possible d'effectuer la pull request de l'US 11 (qui solutionnera les problèmes que tu exposes sur la 13 ), et traiter la 13 par la suite ? 

Concernant les règles, voici ci-après le déroulement d'un tour : 
A)Choix des héros dans la limite de la puissance totale,
B) Accès deckboard :   Simulation d'un tour : 

1. On pioche une carte à chaque début de tour sauf au 1er tour où 3 cartes aléatoires parmi celles que tu as choisi apparaîtront dans ta main (au centre en bas), le reste sera dans ton deck situé à droite,
2. On peut choisir de poser 1 ou zéro carte sur notre board, Chaque carte sur notre board a le droit d'attaquer une fois : Lorsqu'un duel entre deux cartes se produit, les points de vie de celles-ci sont réduites en fonction de leurs points d'attaque respectifs (Hearth-Stone),
3 On clôture notre tour en appuyant sur le bouton End Turn ou  lorsque le délai est passé,
4) Tu gagneras lorsque l'ordinateur n'a plus de carte à disposition.

Merci, on reste à ta dispo.

2020-05-04 13:17 UTC, closed without merging

2020-05-04 13:17 UTC, Astarosa commented
merge all us