#US0 test
WildCodeSchool/lyon-js-03-20-p2-g3 pull request #4
Opened 2020-04-09 13:57 UTC by Astarosa

Vérifie steeeeeeeeeeeeuplait

2020-04-09 14:01 UTC, vbouault requested changes

2020-04-09 14:01 UTC, vbouault commented on cbh/src/App.js
> +      <h1>Cards Battlle of Heroes</h1>
t’écris comme une chèvre, c'est battle !

2020-04-09 14:06 UTC, vbouault commented on cbh/src/App.js
> +      <h1>Cards Battle of Heroes</h1>
nice

2020-04-09 14:06 UTC, vbouault approved these changes

2020-04-09 14:06 UTC, vbouault commented on cbh/src/App.js
> +      <h1>Cards Battle of Heroes</h1>
nice

2020-04-09 14:25 UTC, vbouault commented on cbh/src/App.js
> +      <h1>Cards Battle of Heroes</h1>
ok

2020-04-09 14:26 UTC, vbouault commented on cbh/src/App.js
> +      <h1>Cards Battlle of Heroes</h1>
ok

2020-04-09 14:27 UTC, vbouault approved these changes

2020-04-09 14:27 UTC, vbouault commented on cbh/src/App.js
> +      <h1>Cards Battle of Heroes</h1>
ok

2020-04-09 17:11 UTC, ComicScrip requested changes
Le contenu du dossier "cbh" devrait se trouver à la racine du projet
Hint : `mv cbh/* ./ && mv cbh/.gitignore ./.gitignore && rm -rf ./cbh`

2020-04-10 09:26 UTC, Astarosa commented
> 
> 
> Le contenu du dossier "cbh" devrait se trouver à la racine du projet
> Hint : `mv cbh/* ./ && mv cbh/.gitignore ./.gitignore && rm -rf ./cbh`

C'est fait cf : commit 38f031b5eb0e736da966265cfdd794be42acdb84

2020-04-13 10:45 UTC, ComicScrip approved these changes

2020-04-13 10:45 UTC, merged